spring.application.name=jaulas

spring.datasource.url=jdbc:postgresql://ep-patient-math-aqv0vmd5-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_cjT27MsAzCoX
server.port=8082

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true